### ISSUE TITLE
A error

### ISSUE THREAD

**Issue by lt2228** [skim-aero/MTT_Sim#1]
main.m--line71  **x1(i+1) = x1(i)+vx1*t(i)+0.5*ax1*t(i)^2;** should exchange -**-x1(i+1) = x1(1)+vx1*t(i)+0.5*ax1*t(i)^2;**
so as y1 y2 x2

**Comment by skim-aero** [comment]
Thank you for raising issue. I checked and updated the equations and the parameters accordingly. I updated the constant acceleration model with proper velocity update.

**Comment by lt2228** [comment]
Can you tell me the reference of this kernel GNN algorithm? Thank you very much!

**Comment by skim-aero** [comment]
I don't have any reference for the kernel GNN for now - that approach is just a trial by my side to project the data into kernel space and perform the data association with GNN on kernel space. I'll post on the README file if there is any document you can have a look. Thanks!
